### ISSUE TITLE
关于农历的问题

### ISSUE THREAD

**Issue by liuning9** [Lixucheng/Simple-Calendar#4]
1 对春节/除夕这两个的计算有问题
2 农历通常分大小月 小月一半29天..- - 好像没判断这个 所以再一次错误计算之后的农历日期全都是错误的

**Comment by Lixucheng** [comment]
你好，可不可以告诉我一下那个日期开始出错，方便我改一下

**Comment by liuning9** [comment]
2017.9.20 这个地方应该是六月初一 9.19是29已经是上一个月的结束 上一个月应该为闰月( 我对比过百度日历以及其他..也看了代码..可能就是闰月没有计算对吧.. )

**Comment by wangmiaoduan** [comment]
农历节日转为新历错误了 现在有两个清明
